extends Node

# Regression test: loads docs/fairness-vectors.json and confirms the current
# FairSeed implementation produces byte-identical outputs for every vector.
# The vectors are generated by scripts/gen_fairness_vectors.py (independent
# Python reference). If this scene fails, either the Godot implementation
# drifted from spec OR the vectors are stale — compare hashes to diagnose.

func _ready() -> void:
	var vectors := _load_vectors()
	if vectors.is_empty():
		push_error("could not load fairness-vectors.json")
		get_tree().quit(1)
		return

	var total := 0
	var failed := 0
	for v in vectors["vectors"]:
		total += 1
		if not _run_vector(v):
			failed += 1

	print("TEST_VECTORS: %d/%d passed" % [total - failed, total])
	get_tree().quit(0 if failed == 0 else 1)

func _run_vector(v: Dictionary) -> bool:
	var name: String = v["name"]
	var inputs: Dictionary = v["inputs"]
	var expected: Dictionary = v["expected"]

	var server_seed := FairSeed.from_hex(String(inputs["server_seed_hex"]))
	var round_id: int = int(inputs["round_id"])
	var client_seeds: Array = inputs["client_seeds"]
	var slot_count: int = int(inputs["slot_count"])

	# 1. Commit hash.
	var hash_bytes := FairSeed.hash_server_seed(server_seed)
	var hash_hex := FairSeed.to_hex(hash_bytes)
	if hash_hex != String(expected["server_seed_hash_hex"]):
		push_error("[%s] server_seed_hash mismatch\n  expected %s\n  got      %s" % [name, expected["server_seed_hash_hex"], hash_hex])
		return false

	# 2. Per-marble hashes + colors — exercises _hash_marble and derive_marble_colors.
	var per_marble: Array = expected["per_marble_hashes"]
	for i in range(per_marble.size()):
		var want: String = String(per_marble[i]["hash_marble_hex"])
		var got_bytes := FairSeed._hash_marble(server_seed, round_id, String(client_seeds[i]), i)
		var got: String = FairSeed.to_hex(got_bytes)
		if got != want:
			push_error("[%s] marble %d hash mismatch\n  expected %s\n  got      %s" % [name, i, want, got])
			return false
	var derived_colors := FairSeed.derive_marble_colors(server_seed, round_id, client_seeds)
	for i in range(per_marble.size()):
		var want_rgba: int = int(per_marble[i]["color_rgba_u32"])
		var got_rgba: int = FairSeed.color_to_rgba32(derived_colors[i])
		if got_rgba != want_rgba:
			push_error("[%s] marble %d color mismatch\n  expected 0x%08x\n  got      0x%08x" % [name, i, want_rgba, got_rgba])
			return false

	# 3. Spawn slots — end-to-end with probing.
	var derived := FairSeed.derive_spawn_slots(server_seed, round_id, client_seeds, slot_count)
	var want_slots: Array = expected["spawn_slots"]
	if derived.size() != want_slots.size():
		push_error("[%s] slot count mismatch: expected %d got %d" % [name, want_slots.size(), derived.size()])
		return false
	for i in range(derived.size()):
		if int(derived[i]) != int(want_slots[i]):
			push_error("[%s] slot mismatch at marble %d: expected %d got %d" % [name, i, want_slots[i], derived[i]])
			return false

	print("  [%s] OK (%d marbles, slot_count=%d)" % [name, client_seeds.size(), slot_count])
	return true

func _load_vectors() -> Dictionary:
	var abs_path := ProjectSettings.globalize_path("res://..").path_join("docs/fairness-vectors.json")
	var f := FileAccess.open(abs_path, FileAccess.READ)
	if f == null:
		push_error("open failed: %s (err=%d)" % [abs_path, FileAccess.get_open_error()])
		return {}
	var text := f.get_as_text()
	f.close()
	var parsed = JSON.parse_string(text)
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("JSON parse failed for %s" % abs_path)
		return {}
	return parsed
